
COL_BLACK = (  0,  0,  0)
COL_WHITE = (255,255,255)
COL_BLUE  = (  0,  0,255)
COL_GREEN = (  0,255,  0)
COL_RED   = (255,  0,  0)

ACTION_IDLE = 0
ACTION_MOVL = 1
ACTION_MOVR = 2
ACTION_MOVU = 3
ACTION_MOVD = 4

# Debug message level
# -1: No debug message on console
# -0: Print every debug message
# 1~: Print debug level, lower means more frequent message
CONFIG_DEBUG_MAIN = 1
CONFIG_DEBUG_INSTANCE = 1
CONFIG_DEBUG_GAME = -1

CONFIG_INSTANCE_COUNT = 5
CONFIG_PLAYER_ENABLE = False

CONFIG_HP_MAX = 100
CONFIG_HP_INITIAL = 50
CONFIG_HP_DECAY_MODE = 0 # 0 = Absoulte, 1 = portion
CONFIG_HP_DECAY_VALUE = 1
CONFIG_DMG_BASE = 5
CONFIG_DMG_COEF_HP = 0.1
CONFIG_DMG_COEF_REFLECT = 0.5
CONFIG_DMG_COEF_VAMPIRE = 0.2

CONFIG_AREA_W = 10
CONFIG_AREA_H = 10

CONFIG_CELL_W = 60
CONFIG_CELL_H = 60

CONFIG_RESOURCE_MAX = 10
CONFIG_RESOURCE_SPAWN_METHOD = 0 # 0:Basic Method
CONFIG_RESOURCE_SPAWN_RATE = 0.06

def print_config():
    print("Config list")

