
# Debug message level
# -1: No debug message on console
# -0: Print every debug message
# 1~: Print debug level, lower means more frequent message
DEBUG_MAIN = 1
DEBUG_INSTANCE = 1
DEBUG_GAME = -1
DEBUG_AGENT = -1

TEST_AUTOMATIC = True #Still, you can halt with <Space>
TEST_STEP_PER_SECOND = 20
TEST_SAVE_ENABLED = True
TEST_SAVE_PATH = ""
TEST_LOAD_ENABLED = False
TEST_TURN_LENGTH = 5000

MAIN_PRINT_TURN_FREQUENCY = 500

GAME_AREA_WIDTH = 10
GAME_AREA_HEIGHT = 10
GAME_INSTANCE_COUNT = 5
GAME_PLAYER_ENABLE = False

GAME_STATE_METHOD = "basic"
GAME_INSTANCE_SIGHT = 2

GAME_RESOURCE_METHOD = "basic"
# METHOD basic
GAME_RESOURCE_MAX = 10
GAME_RESOURCE_SPAWN_RATE = 0.06

# INSTANCE VARIABLES
INSTANCE_HP_MAX = 100
INSTANCE_HP_INITIAL = 50

INSTANCE_DECAY_MODE = 0 # 0 = Absoulte, 1 = portion
INSTANCE_DECAY_VALUE = 1

INSTANCE_DAMAGE_BASE = 3 # Base damage
INSTANCE_DAMAGE_PERCENT_HP = 0.1 # Attack damage
INSTANCE_DAMAGE_PERCENT_REFLECT = 0.4 #
INSTANCE_DAMAGE_PERCENT_VAMPIRE = 0.0 # Absorbs other instance's hp

INSTANCE_REWARD_MODEL = "basic"

# AGENT VARIABLES
AGENT_HIDDEN_CHANNEL = 256
AGENT_IS_REVIVABLE = True
AGENT_MEMORY_LENGTH = 500
AGENT_BASE_COOLTIME = 10 # In turns
AGENT_EPS_START = 0.9
AGENT_EPS_END = 0.05
AGENT_EPS_DECAY = 200
AGENT_GAMMA = 0.8
AGENT_LR = 0.001
AGENT_BATCH_SIZE = 32

# DRAW
DRAW_CELL_WIDTH = 60
DRAW_CELL_HEIGHT = 60
DRAW_FONT_SIZE_BIG = 20
DRAW_FONT_SIZE_SMALL = 12

DRAW_COL_BLACK = (  0,  0,  0)
DRAW_COL_WHITE = (255,255,255)
DRAW_COL_BLUE  = (  0,  0,255)
DRAW_COL_GREEN = (  0,255,  0)
DRAW_COL_RED   = (255,  0,  0)

ACTION_COUNT = 5
ACTION_IDLE = 0
ACTION_MOVL = 1
ACTION_MOVR = 2
ACTION_MOVU = 3
ACTION_MOVD = 4
